
build:centos8:
  image: alazartech/centos8:2.1.0
  script:
    - conan remote remove bincrafters
    - yum install -y sudo
    - cd recipes/qt/6.x.x
    - CONAN_SYSREQUIRES_MODE=enabled conan create . qt/6.2.2@alazar/stable --build missing -s ${BUILD_TYPE} -o qt:shared=True
    - conan upload qt/6.2.2@alazar/stable -r ottawa
  parallel:
    matrix:
      - BUILD_TYPE: ["build_type=Release", "build_type=Debug"]
  tags:
    - docker

build:ubuntu20.04:
  image: alazartech/centos8:2.1.0
  script:
    - conan remote remove bincrafters
    - yum install -y sudo
    - cd recipes/qt/6.x.x
    - CONAN_SYSREQUIRES_MODE=enabled conan create . qt/6.2.2@alazar/stable --build missing -s ${BUILD_TYPE} -o qt:shared=True
    - conan upload qt/6.2.2@alazar/stable -r ottawa
  parallel:
    matrix:
      - BUILD_TYPE: ["build_type=Release", "build_type=Debug"]
  tags:
    - docker

build:windows:
  image: alazartech/vs2019:2.1.0
  script:
    - conan remote remove bincrafters
    - cd recipes/qt/6.x.x
    - conan create . qt/6.2.2@alazar/stable --build missing -s ${BUILD_TYPE} -o qt:opengl=dynamic -o qt:shared=True
    - conan upload qt/6.2.2@alazar/stable -r ottawa
  parallel:
    matrix:
      - BUILD_TYPE: ["build_type=Release", "build_type=Debug"]
  tags:
    - docker-windows
