variables:
    BUILD_DIR: recipes/llvm/all
    RECIPE: llvm/13.0.0@alazar/stable

build:centos8-gcc10:
  image: alazartech/centos8:2.1.0
  script:
    - dnf install -y gcc-toolset-10-gcc gcc-toolset-10-gcc-c++
    - source /opt/rh/gcc-toolset-10/enable
    - conan profile update settings.compiler.version=10 default
    - conan remote remove bincrafters
    - yum install -y sudo
    - cd ${BUILD_DIR}
    - CONAN_SYSREQUIRES_MODE=enabled conan create . ${RECIPE} --build missing -s ${BUILD_TYPE} -o qt:shared=True
    - conan upload ${RECIPE} -r ottawa --all
  parallel:
    matrix:
      - BUILD_TYPE: ["build_type=Release", "build_type=Debug"]
  tags:
    - docker

build:windows:
  image: alazartech/vs2019:2.1.0
  script:
    - conan profile update settings.compiler.version=16.11 default
    - conan remote remove bincrafters
    - cd ${BUILD_DIR}
    - conan create . ${RECIPE} --build missing -s ${BUILD_TYPE} -o qt:opengl=dynamic -o qt:shared=True
    - conan upload ${RECIPE} -r ottawa --all
  parallel:
    matrix:
      - BUILD_TYPE: ["build_type=Release", "build_type=Debug"]
  tags:
    - docker-windows
