qt:win:
  image: alazartech/vs2019:2.1.0
  script:
    - conan remote remove bincrafters # Not used anymore
    - cd recipes/qt/6.x.x
    - conan create --build missing -o qt:shared=True ${OPTION} -s build_type=${BUILD_TYPE} . qt/6.2.3@alazar/stable
    - conan upload -r ottawa --all --force qt/6.2.3@alazar/stable
  parallel:
    matrix:
      - OPTION: ["", "-o qt:qttranslations=True"]
        BUILD_TYPE: ["Release", "Debug"]
  stage: build
  tags:
    - docker-windows

qt:ubuntu20:
  image: alazartech/ubuntu20.04:2.1.0
  script:
    - apt-get install -y sudo # Conan wants it
    - conan remote remove bincrafters # Not used anymore
    - cd recipes/qt/6.x.x
    - conan create --build missing -o qt:shared=True ${OPTION} -s build_type=${BUILD_TYPE} . qt/6.2.3@alazar/stable
    - conan upload -r ottawa --all --force qt/6.2.3@alazar/stable
  parallel:
    matrix:
      - OPTION: ["", "-o qt:qttranslations=True"]
        BUILD_TYPE: ["Release", "Debug"]
  stage: build
  tags:
    - docker
